woowacourse-teams/2021-babble

- .github/workflows/back-release.yml
프론트 yml 파일과 확실한 구분을 위해 이름 변경
paths-ignore 명령을 통해 프론트 배포시 백엔드 배포가 반응하지 않도록 변경
> chore: 백엔드 자동배포 관심사 분리

- back/babble/src/main/java/gg/babble/babble/controller/TagController.java
- back/babble/src/main/java/gg/babble/babble/dto/RoomRequest.java
- back/babble/src/main/java/gg/babble/babble/dto/RoomResponse.java
- back/babble/src/main/java/gg/babble/babble/dto/TagRequest.java
- back/babble/src/main/java/gg/babble/babble/dto/TagResponse.java
- back/babble/src/main/java/gg/babble/babble/service/TagService.java
- back/babble/src/main/resources/static/docs/api-docs.html
- back/babble/src/test/java/gg/babble/babble/controller/TagControllerTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/ApiDocumentationIntegrationTest.java
- back/babble/src/test/java/gg/babble/babble/service/TagServiceTest.java
- 전체 태그를 불러오는 기능 구현
- 수정된 API 명세에 맞춰, 요청 응답에 String 필드로 관리하던 tag를 포장 하도록 수정
- `ApiDocumentationIntegrationTest.class` 에서 문제 발생
기존에는 String으로 관리해서 hasItem으로 처리가 되었던것 같으나, 포장한뒤 문제가 되는중.  
hasItem 내부에 리스트형태로 넣어주어도 문제가 발생
내부값을 뽑아와서 비교를 해보아도 문제가 발생  
이부분에 대한 해결책을 RestDocs 관련 지식이 미흡한 상태로는 찾지못함
---
**요청**의 경우에도 tag 포장이 필요한지에 대한 의문이 생김.
응답에 관해서는 나중에 다른 정보를 더 담을 가능성이 있어, 포장하는게 맞지만   
**요청**에서는 key값으로만 쓰이는 이름만 보내줘도 문제가 없을것으로 사료됨.
> feat : 태그 관련 기능 구현 및 리팩토링 

- front/src/components/SearchInput/SearchInput.js
- front/src/hooks/useDebounce.js
Closes #
- 검색창 컴포넌트의 onChange에 자동완성 기능을 달아놨는데, onChange가 발생할 때마다 자동완성이 일어나면 계산도 너무 자주 일어나고, 리렌더링도 너무 자주 일어나서 매우 비효율적인 동작이 수행되게 됩니다. 
- 그래서 debounce를 통해 자동완성 기능의 수행 시점을 늦춰서 조금 더 효율적으로 동작하게끔 만들어줬습니당
- useDebounce를 콜백 함수를 받는 custom hook으로 만들어놨는데, 인자로 들어가는 callback function은 주로 이벤트 리스너 함수이다보니, 호이스팅 문제로 인해 hook을 맨 위에 선언해놓지 못하는 문제가 있었습니다.
- 그래서 useDebounce hook 자체로 콜백 함수를 받는 것이 아니라, useDebounce가 return하는 'debounce' 라는 함수가 직접 콜백 함수를 받아서 실행하도록 변경해주었습니다.
- 그렇게 하니깐, 또 인자로 '함수'를 넣어줘야 하기 때문에 `() => {}` 꼴로 이벤트 리스너 함수를 한 번 더 감싸줘야하는 번거로움이 있었습니다. inline function으로 집어넣으니 코드가 너무나도 못생겨서, debounce를 씌운 별도의 함수를 하나 더 선언해줬습니다.
```javascript
const onChangeInputDebounced = (e) => {
debounce(() => onChangeInput(e));
};
```
- 추후에 useDebounce 훅을 `여러 개의 timer 키를 객체 혹은 배열로 관리하는 일반 함수`로 만들면 어떨까 생각중. 그렇게 하면 여러 개의 타이머를 …
> fix: 검색창 컴포넌트 자동완성 기능에 debounce 적용

- back/babble/src/main/java/gg/babble/babble/DataLoader.java
- back/babble/src/main/java/gg/babble/babble/controller/GameController.java
- back/babble/src/main/java/gg/babble/babble/domain/Game.java
- back/babble/src/main/java/gg/babble/babble/domain/room/MaxHeadCount.java
- back/babble/src/main/java/gg/babble/babble/dto/GameImageResponse.java
- back/babble/src/main/java/gg/babble/babble/service/GameService.java
- back/babble/src/test/java/gg/babble/babble/domain/MaxHeadCountTest.java
- back/babble/src/test/java/gg/babble/babble/domain/repository/RoomRepositoryTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/GameApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/GameServiceTest.java
단일 게임 이미지 요청, 전체 게임 이미지 목록 요청 구현
게임 이미지가 등록되지 않은 경우, default 이미지를 사용하도록 매핑했습니다.
추후 게임의 이미지 필드`Game.image(string)`을 원시값 포장 리팩토링을 진행하면서 보완할 계획입니다.
> 게임 이미지 요청 API 기능 구현

- back/babble/src/main/java/gg/babble/babble/controller/GameController.java
- back/babble/src/main/java/gg/babble/babble/domain/Game.java
- back/babble/src/main/java/gg/babble/babble/domain/Games.java
- back/babble/src/main/java/gg/babble/babble/domain/room/Rooms.java
- back/babble/src/main/java/gg/babble/babble/dto/IndexPageGameResponse.java
- back/babble/src/main/java/gg/babble/babble/service/GameService.java
- back/babble/src/test/java/gg/babble/babble/domain/GamesTest.java
- back/babble/src/test/java/gg/babble/babble/domain/repository/RoomRepositoryTest.java
- back/babble/src/test/java/gg/babble/babble/domain/room/RoomsTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/GameApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/GameServiceTest.java
- 게임에 참가중인 인원 수에 따라 내림차순 정렬된 게임 리스트를 반환하도록 했습니다.
- 도메인 테스트 부족한 부분이 없는지 확실하지 않네요...
- 양방향 매핑이 제대로 이루어졌는지 확인이 미흡합니다.
- 일급 컬렉션으로 로직이 서비스 레이어로 노출되지 않게 최대한 숨겨봤는데, 괜찮을까요?
> 초기 페이지 게임 리스트 조회 API 구현

- front/index.js
- front/package-lock.json
- front/package.json
- front/src/App.js
- front/src/chunks/TagList/TagList.scss
- front/src/components/Button/Button.scss
- front/src/components/Button/Button.stories.js
- front/src/components/Modal/Modal.scss
- front/src/components/Room/Room.scss
- front/src/components/SearchInput/DropdownInput.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/MakeRoom/MakeRoom.scss
- front/style/_variables.scss
Closes #
- 제일 작은 버튼 컴포넌트 추가
- Dropdown Input의 화살표를 클릭해도 더 이상 input이 focus 되지 않음
- TagList가 여러 줄이 될 경우에 gap 추가, 태그 정렬을 좌측 정렬로 수정
- Modal에 z-index를 추가
- 방 컴포넌트에 hover, active 애니메이션 추가
- 방 생성하기 제목 크기 확대
- 마크업이라 딱히 음슴 ㅋ
> feat: 방 생성 페이지 마크업 마무리

- back/babble/src/main/java/gg/babble/babble/DataLoader.java
- back/babble/src/main/java/gg/babble/babble/domain/repository/TagRepository.java
- back/babble/src/main/java/gg/babble/babble/domain/room/TagRegistrationsOfRoom.java
- back/babble/src/main/java/gg/babble/babble/domain/tag/Tag.java
- back/babble/src/main/java/gg/babble/babble/dto/CreatedRoomResponse.java
- back/babble/src/main/java/gg/babble/babble/dto/FoundRoomResponse.java
- back/babble/src/main/java/gg/babble/babble/dto/TagRequest.java
- back/babble/src/main/java/gg/babble/babble/dto/TagResponse.java
- back/babble/src/main/java/gg/babble/babble/service/TagService.java
- back/babble/src/test/java/gg/babble/babble/domain/repository/RoomRepositoryTest.java
- back/babble/src/test/java/gg/babble/babble/domain/repository/TagRepositoryTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/RoomApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/TagApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/RoomServiceTest.java
- back/babble/src/test/java/gg/babble/babble/service/TagServiceTest.java
Closes #
태그 이름을 Id로 사용하고 있던 것을 별도의 Integer Id를 사용하도록 수정했습니다.
따로 없었지만, DataLoader와 테스트 코드의 분리의 필요성을 느꼈습니다.
> feat: 태그 Id 추가

- back/babble/build.gradle
> fix: api-docs가 덮어쓰기 되도록 수정

- front/src/pages/ChattingRoom/ChattingRoom.js
Closes #
- unsubscribe 이전에 퇴장 메시지를 출력하도록 수정
> fix: unsubscribe 이전에 퇴장 메시지를 send하도록 수정

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
- front/src/components/NicknameSection/NicknameSection.js
- front/src/components/NicknameSection/NicknameSection.scss
- front/src/contexts/ChattingModalProvider.js
- front/src/contexts/UserProvider.js
- front/src/pages/ChangeNickname/ChangeNickname.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/RoomList/RoomList.js
Closes #
- 웹소켓 readyState가 OPEN일 때를 기다리는 waitForConnectionReady 메소드 추가
- sendMessage 메소드 추상화
- 채팅창 모달이 열려있을 때 닉네임 변경이 불가능하도록 수정
- 닉네임 변경을 요구하는 말풍선이 최초 닉네임 변경 이후 보이지 않도록 수정
- StompJS v5가 connect 시와 disconnect 시 각각 다른 sessionId를 서버에 전달한다.
- 서버에서는 connect 시에 전달받은 sessionId를 가지고 해당 유저의 disconnect 여부를 판단하기 때문에 로직이 제대로 작동하지 않는다.
- StompJS v4로 다시 마이그레이션 후 send의 정확도 보강을 위해 waitForConnectionReady 메소드를 추가하였다.
> fix: 웹소켓 채팅 send 시 readyState가 OPEN 상태일 때만 전송하도록 수정

- front/src/contexts/UserProvider.js
- front/src/pages/RoomList/RoomList.js
Closes #
-  방 생성 후 방 목록 페이지 재입장 시 닉네임이 변경되는 문제 수정
- 채팅 방이 만들어질 때 방 목록이 리렌더되는데, 리렌더 되면 닉네임이 새로 발급되기 때문에 생긴 문제였음
> fix: 방 생성 후 방 목록 페이지 재입장 시 닉네임이 변경되는 문제 수정

- front/src/components/SpeechBubble/SpeechBubble.scss
Closes #
- 영어 텍스트가 길어져도 말풍선을 벗어나지 않도록 수정
> fix: 영어 텍스트가 길어져도 말풍선을 벗어나지 않도록 수정

- back/babble/build.gradle
- back/babble/src/main/java/gg/babble/babble/domain/room/MaxHeadCount.java
- back/babble/src/main/resources/application-prod.properties
- back/babble/src/main/resources/application-test.properties
- back/babble/src/main/resources/db/migration/V1__init.sql
Closes #289 
- 프로덕션용 db가 drop되지 않게 수정
- db 스키마 수정시 매번 db에 접속하는 것이 아니라 db migration을 진행하도록 수정(flyway 도입)
`properties` 파일에 아래의 설정을 추가하여 해결했다.
```java
spring.jpa.hibernate.ddl-auto=validate
```
예를들어, 서비스가 확장되면서 `User`에 `Age`컬럼이  추가되었을 때, `Age`가 not null 이라면 기존의 사용자 데이터는 어떻게 처리하는 것이 좋을까?
→ 구글링 결과, 방법은 1. not null을 포기하거나 2. default value를 설정하거나 두 가지 방법 밖에없다. 상태로 컬럼을 추가하는 수밖에 없다. (어떻게 보면 당연하다 우리가 사용자의 나이를 추측할 순 없으니까)
기존 데이터는 null로 두고 이후에 생성되는 데이터에서는 null이 들어오지 못하도록 DTO에서 null 값체크를 하도록 구현한다.
기존 데이터에 default value를 설정하고 값을 설정하도록 한다. 이후에 이 default 값을 사용하고 싶지 않다면 default value에 대한 제약사항을 삭제하면 된다. 이 방법의 경우, 위 예시인 나이에는 맞지 않을 거라는 생각이 든다.
[https://stackoverflow.com/questions/64025530/add-not-null-column-without-default-but-with-values](https://stackoverflow.com/questions/64025530/add-not-null-column-with …
> feat: flyway로 db 마이그레이션 적용

- back/babble/src/main/resources/application-local.properties
Test 인스턴스에서 시간 변경은 잘 진행됐는데, 재부팅 후에도 시간이 유지되는가 테스트를 위해서 재부팅을 진행했다가 DB를 담당하는 도커 컨테이너의 IP주소 값이 `172.17.0.3` 에서 `172.17.0.2`로 변경됐습니다.
> fix: local 프로필이 사용하는 DB 컨테이너 IP주소 변경

- back/babble/build.gradle
Closes #347 
로컬상에서 테스트했을때 커버러지 표시되는것을 확인했습니다. `78.8%`
- jacoco를 추가하여, 테스트 커버러지가 sonarcube에서 표시되도록 구현
```java
plugins {
...
id 'jacoco'
}
jacoco {
toolVersion = "0.8.7"
}
jacocoTestReport {
reports {
html.enabled true
csv.enabled true 
xml.enabled true
}
}
```
- jacoco 기본설정 추가
- **실패(커버러지 0%가 지속되었다.)**
- `jacoco/test.exec`가 있으나 적용이 되지않음.
- 서버 재시작 : https://community.sonarsource.com/t/sonarqube-code-coverage-is-0/38807
- **실패**
- 옵션추가 : https://tomgregory.com/how-to-measure-code-coverage-using-sonarqube-and-jacoco/
```java
jacocoTestReport {
reports {
html.enabled true
csv.enabled true 
xml.enabled true 
}
}
test.finalizedBy jacocoTestReport
```
> we use finalizedBy to ensure that the test report is always generated after tests are run
- `test.finalizedBy jacocoTestReport` 을 넣어주었다.
- …
> chore: sonarCube 테스트 커버러지를 나타내기 위한 jacoco 추가

- back/babble/src/main/java/gg/babble/babble/domain/Game.java
- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
- back/babble/src/main/java/gg/babble/babble/util/UrlParser.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketChattingTest.java
- back/babble/src/test/java/gg/babble/babble/domain/UserTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/UserApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/UserServiceTest.java
Closes #307 #190
유저 기본 아마타를 랜덤으로 생성하게 구현했다.
String의 hashCode() 메소드를 이용해서 구현하려고 했으나 hashCode의 리턴 타입 int라 오버플로우로 음수가 나오는 경우가 발생했다.
int의 최소 값을 빼는 방법으로 이를 해결했다.
```java
long avatarIndex = ((long) nickname.hashCode() - Integer.MIN_VALUE) % NUMBER_OF_AVATAR;
```
> feat: 랜덤 아바타 기능 구현

- .github/workflows/back-main.yml
- .github/workflows/back-release.yml
배포 빌드와 소나큐브 빌드 사이 `needs` 키워드를 통해 의존성을 추가하여 배포 빌드가 무조건 우선시 되도록 설정했습니다.
만약 배포 빌드가 실패할 경우, 배포 빌드에 의존하는 소나큐브 빌드는 진행되지 않습니다.
> chore: 워크플로우 동작 사이 의존성 부여

- back/babble/src/main/resources/db/migration/V2__add_column_deleted.sql
mariaDB는 컬럼명 수정 시 기존 타입까지 함께 입력해줘야된다.
<https://bskyvision.com/1026>
> fix: syntax error 수정

- back/babble/src/main/java/gg/babble/babble/domain/tag/Tag.java
> fix: 태그 이름이 null일 수 있는 버그 수정 (#397)

- back/babble/src/main/java/gg/babble/babble/controller/GameController.java
- back/babble/src/main/java/gg/babble/babble/controller/RoomController.java
- back/babble/src/main/resources/static/docs/api-docs.html
- back/babble/src/test/java/gg/babble/babble/restdocs/GameApiDocumentTest.java
Closes #390 
- https://www.notion.so/POST-201-vs-200-fd061db126ff46a29aa2ad175351ae42
User Created도 201로 반환할까 하다가, 현재 UserId를 사용하는 부분이 전혀 없어서 일단 200으로 현상유지 해놓았습니다.
- https://github.com/woowacourse-teams/2021-babble/blob/58dfb31d2f2293f1e75cd07ecce7bb6d8e268e2b/back/babble/src/main/java/gg/babble/babble/controller/UserController.java#L23
- 전자레인지 돌리면서 이슈목록 슥보다가, 별거아니길래 손댓다가 테스트만 30분넘게 쳐다봤습니다. -_-
> post api 201 상태코드 변경

- front/src/pages/GameList/GameList.js
- front/src/pages/GameList/GameList.scss
- front/style/_mixins.scss
Closes #
- 별도 제작 배너 이미지 적용
- 스크롤 sticky 경계에 걸치면 스타일이 빠른 속도로 toggle되는 버그 수정
> fix: 스크롤 버그 수정 및 배너 이미지 적용

- back/babble/src/main/java/gg/babble/babble/domain/Session.java
- back/babble/src/main/java/gg/babble/babble/domain/game/Game.java
- back/babble/src/main/java/gg/babble/babble/domain/room/Room.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketRoomUpdateTest.java
- back/babble/src/test/resources/websocket-context.sql
논리적 삭제 사용하는 Entity에 `@Where` 어노테이션 사용
```java
@EntityListeners(AuditingEntityListener.class)
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
public class Room {
@OneToMany(mappedBy = "room")
private final List<Session> sessions = new ArrayList<>();
//...
}
```
```java
@EntityListeners(AuditingEntityListener.class)
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
public class Session {
@Column(nullable = false)
private boolean deleted = false;
//...
public void delete() {
if (user.isLinkedSession(this)) {
user.unLinkSession(this);
}
if (room.containsSession(this)) {
room.exitSession(this);
}
deleted = true;
}
}
```
`Session`은 논리적 삭제를 사용하고 있는데, `Room`의 `sessions`필드가 지연로딩 될 때, 논리적 삭제를 사용하고 있는 것을 모르기 때문에 모든 session을 가지고 오는 문제가 있었다.
Hibernate에서 제공해주는 어노테이션인 …
> fix: 유저가 방에서 제대로 나가지지 않는 버그 수정

- back/babble/src/main/resources/application-dev.yml
Datasource 관련 옵션 중 password 와 url을 제외한 옵션들은 application-dev.yml 에서 관리하도록 수정
Closes #
> refactor: application-dev.yml 에서 데이터베이스 URL만 주석처리하도록 변경

- back/babble/src/main/resources/application-dev.yml
Datasource 관련 옵션 중 password 와 url을 제외한 옵션들은 application-dev.yml 에서 관리하도록 수정
Closes #
> refactor: application-dev.yml 에서 데이터베이스 URL만 주석처리하도록 변경 (#551)

- back/babble/src/main/java/gg/babble/babble/config/AdminAccessInterceptor.java
- back/babble/src/test/java/gg/babble/babble/restdocs/GameApiDocumentTest.java
IP 검증할 때, nginx의 IP를 확인하고 있는 문제를 해결하기 위해서 x-forwarded-for 헤더를 확인하도록 수정합니다.
> feat: x-forwarded-for 헤더를 사용해서 IP를 확인하도록 수정

- back/babble/src/main/java/gg/babble/babble/domain/repository/s3repository/AbstractS3Repository.java
Closes #559
--
`URLConnection.guessContentTypeFromName` 메서드에서 추측하지 못하는 파일의 종류이면 null 타입이 반환되는 문제가 있었습니다. 이를 해결하기위해 null 체크를 하도록 수정했습니다.
> fix: 이미지 목록 조회 시 발생하는 에러 수정

- .github/workflows/back-release-deploy.yml
- back/babble/src/main/resources/application-dev.yml
- bastion과 연결 완료
- namecheap 사이트에서 test-api 도메인으로 향하는 주소 `TEST` 에서 `TEST-WEB-SERVER`로 변경해두었음.
- 로깅 잘 되는거같음.
- bastion과 연결 완료
- `CICD(github actions)` → `TEST-WAS` 자동배포를 위해 `CICD` 인스턴스 내부와 `TEST-WAS` 인스턴스 내부 연결 설정 완료
- `CICD` 배포 설정 변경에 따른 `release-deploy.yml` 파일 변경
- 데이터베이스 연결 설정 변경에 따른 `application-dev.yml` 파일 변경
- 더 이상 기존 `TEST` 인스턴스처럼 데이터베이스 IP가 변경될 위험이 사라짐.
- `CICD`를 통한 배포까지 해보려 했으나, 02:30 기준 PR OK 싸인 넣어줄 사람 없어서 진행 안됨...
- `TEST-WAS`에서 git clone 받고 직접 빌드 후 도커에 올려서 연결 테스트는 해보았음. 
- bastion과 연결 완료
- 계정 및 스키마 생성 완료
- 데이터베이스 쪽 설정은 크게 건드릴거 없을듯?
- 데이터베이스에 데이터만 채워넣으면 되는 상태.
- 근데 너무 피곤해서 내일 하겠음..
- 로깅 관련 설정 건드릴거 많을듯..
- 다행히 TEST-WEB-SERVER는 지가 알아서 로그 잘 찍어주는 중 
- EC2별 보안그룹 관련 설정도 몇 가지 빼먹은게 있을거 같음.
- 문서화 해두었던 자료들 하나씩 확인하면서 빼먹은 설정 있는지 체크 필요해보임.
> refactor: 테스트용 EC2 인스턴스 분할에 따른 리팩토링

- back/babble/src/docs/custom-snippets/chat-room-connect/web-socket-response.adoc
- back/babble/src/test/java/gg/babble/babble/restdocs/websocket/ChattingTest.java
Closes #
- 웹소켓 연결시도시 200이 올바른 응답이라고 잘못 판단하는 테스트를 제거했습니다.
- **연결 성공시에는 101 응답코드를 받아야합니다.**
- 하지만 이부분은 RestAssured를 통해서 확인이 불가능합니다.
- 웹소켓 연결시 필요한 헤더들을 직접 넣어주어 보았으나, 웹소켓 연결을 실패하는것을 확인했습니다. 
- 아래 다른 테스트에서 웹소켓 연결 자체도 같이 테스트가 되고 있다고 판단하여, 현재 테스트는 잘못된테스트이며, 추가적으로 개선할 방법을 찾을 필요성이 없다고 판단하여 제거했습니다.
postman의 웹소켓 connect시 들어가는 헤더들을 비슷하게 본떠서, HTTP GET 요청으로 넣어보았으나 101을 반환받지 못했습니다.
> fix: 잘못되어있던 테스트 코드 삭제

- back/babble/gradle/wrapper/gradle-wrapper.properties
Closes #
https://www.cyberkendra.com/2021/12/worst-log4j-rce-zeroday-dropped-on.html?m=1
구버전 log4j 에 제로데이 취약점이 발견됐네요.
2.0 <= Apache log4j2 <= 2.14.1 사이가 영향을 받는 버전입니다.
RCE 공격을 받을 우려가 있습니다.
현재 저희서비스는 2.14.1 이므로 공격 대상안입니다.
https://github.com/tangxiaofeng7/apache-log4j-poc#%E4%BF%AE%E5%A4%8D%E6%96%B9%E6%A1%88
JVM 옵션에 `-Dlog4j2.formatMsgNoLookups=true` 을 추가했습니다.
> Hotfix: log4j 보안 이슈 해결

- back/babble/build.gradle
log4j2 이슈에 따른 버전 업데이트 (2.15.0)
`log4j2.formatMsgNoLookups = true` 에 대해서는 포츈이 이미 진행해주셨음
> fix: log4j2 버전 업데이트
