- front/.storybook/main.js
- front/.storybook/preview.js
- front/global.scss
- front/package-lock.json
- front/package.json
> 프로젝트 설정(Storybook)을 진행한다.

- front/.storybook/main.js
- front/.storybook/preview.js
- front/global.scss
- front/index.html
- front/index.js
- front/package-lock.json
- front/package.json
- front/src/App.js
- front/src/components/Avatar/Avatar.jsx
- front/src/components/Avatar/Avatar.scss
- front/src/components/Avatar/Avatar.stories.js
- front/style/_mixins.scss
- front/style/_variables.scss
- front/webpack.config.js
> feat: 아바타 컴포넌트 구현

- back/babble/src/main/java/gg/babble/babble/BabbleApplication.java
- back/babble/src/main/java/gg/babble/babble/controller/BabbleAdvice.java
- back/babble/src/main/java/gg/babble/babble/controller/ChatController.java
- back/babble/src/main/java/gg/babble/babble/controller/RoomController.java
- back/babble/src/main/java/gg/babble/babble/exception/BabbleException.java
> 백엔드 스켈레톤 코드 작성

- .github/workflows/release.yml
> chore: 테스트 서버용 github actions 생성

- back/babble/src/main/resources/application-local.properties
테스트용 WAS를 test db에 연결하기 위한 properties 파일을 추가했습니다.
> chore: local properties 추가

- .github/workflows/release.yml
- back/babble/src/main/resources/application-local.properties
Dockerfile 경로 문제 해결
db 경로 문제 해결
> fix: 테스트 서버 자동 배포 실패 문제 해결

- .github/workflows/front-release.yml
> fix: 자동 배포 세팅 수정

- back/babble/src/main/java/gg/babble/babble/controller/BabbleAdvice.java
- back/babble/src/main/java/gg/babble/babble/exception/BabbleDuplicatedException.java
- back/babble/src/main/java/gg/babble/babble/exception/BabbleException.java
- back/babble/src/main/java/gg/babble/babble/exception/BabbleIllegalArgumentException.java
- back/babble/src/main/java/gg/babble/babble/exception/BabbleLengthException.java
- back/babble/src/main/java/gg/babble/babble/exception/BabbleNotFoundException.java
> refactor : 예외 발생시 적절한 http status code로 응답하도록 수정, 소켓통신에서 발생한 예외를 처리하도록 수정

- .github/workflows/back-main.yml
- .github/workflows/back-release.yml
- .github/workflows/front-release.yml
> chore: 자동배포 탐지 경로 수정

- .github/workflows/front-main.yml
- front/.releaserc.json
- front/package.json
- main branch, release branch 별도의 workflow 파일 적용
> feat: 프론트 semantic versioning 자동화 세팅

- front/src/chunks/Chatbox/Chatbox.js
- front/src/core/Layout/PageLayout.js
- front/src/core/Layout/PageLayout.scss
- front/src/core/Typography/Typography.scss
Closes #
- 없음
- 기본적인 페이지 구현을 위한 PageLayout 추가
- 없음
> feat: PageLayout 추가

- back/babble/.gitignore
> log 확장자 gitignore 추가

- front/src/App.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/MakeRoom/MakeRoom.scss
- front/src/pages/RoomList/RoomList.js
Closes #198 
- react-router-dom 라이브러리를 활용해 routing 기능 구현
- 아직까진 없슴 ㅎ
> feat: routing 기능 구현

- back/babble/src/docs/asciidoc/api-docs.adoc
- back/babble/src/docs/custom-snippets/chat-receive/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-receive/web-socket-response.adoc
- back/babble/src/docs/custom-snippets/chat-room-connect/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-room-connect/web-socket-response.adoc
- back/babble/src/docs/custom-snippets/chat-room-update/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-room-update/web-socket-response.adoc
- back/babble/src/docs/custom-snippets/chat-send/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-send/web-socket-response.adoc
- back/babble/src/docs/custom-snippets/user-list/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/user-list/web-socket-response.adoc
- back/babble/src/main/resources/static/docs/api-docs.html
build 폴더가 .gitignore 에 등록되어 custom-snippets 가 커밋되지 않음
custom-snippets 폴더 위치 수정
> web socket restdocs 재추가

- back/babble/src/test/java/gg/babble/babble/service/SubscribeAuthServiceTest.java
- 룸 id에 의존적이여서 발생한 버그를 수정했습니다.
> fix: 테스트코드 버그 수정

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
> fix: DB에 JoinedAt 컬럼이 생기지 않는 문제 해결 시도

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
> fix: 빠진 어노테이션 추가

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
> 빠진 어노테이션 추가

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
> fix: LastModifed를 CreatedDate로 수정

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
> refactor: 불필요한 어노테이션 제거

- back/babble/src/main/resources/static/docs/api-docs.html
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketRoomUpdateTest.java
> feat: rest-docs 파일 추가

- .github/workflows/back-main.yml
- .github/workflows/back-release.yml
- back/babble/build.gradle
- back/babble/src/docs/asciidoc/api-docs.adoc
- back/babble/src/docs/custom-snippets/chat-room-update/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-send/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-send/web-socket-response.adoc
- back/babble/src/docs/custom-snippets/user-list/web-socket-response.adoc
- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
- back/babble/src/main/resources/static/docs/api-docs.html
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketRoomUpdateTest.java
Closes #243
웹 소켓 rest docs 문서화
> 웹 소켓 rest docs 문서화

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
Closes #295 
- Cloudfront 배포 시 캐시 무효화 설정
> feature: Cloudfront 배포 시 캐시 무효화 설정

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
> chore: Cloudfront 배포 시 캐시 무효화 설정 (#296)

- front/webpack.config.js
* chore: Cloudfront 배포 시 캐시 무효화 설정
* chore: webpack 번들 파일명 변경
Closes #
제곧내
> chore: webpack bundle 파일명 변경

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
- front/webpack.config.js
Closes #
- Cloudfront 캐시 무효화 설정 초기화
> chore: Cloudfront 캐시 무효화 설정 초기화

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
* chore: Cloudfront 배포 시 캐시 무효화 설정
* chore: webpack 번들 파일명 변경
* chore: Cloudfront 캐시 무효화 설정 초기화
* chore: Cloudfront 배포 시 캐시 무효화 설정
Closes #
- Cloudfront 배포 시 캐시 무효화 설정
> chore: Cloudfront 배포 시 캐시 무효화 설정

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
Closes #
- front release yml 파일 수정
> fix: front-release-yml

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
* fix: front-release-yml
Closes #
> fix: front-release-yml (#314)

- .github/workflows/back-release.yml
- back/babble/build.gradle
> chore: 소나큐브 의존성 추가 및 CICD 자동화 파일 수정

- .github/workflows/back-release.yml
> chore: CICD 자동화 파일 오타 수정

- back/babble/src/test/java/gg/babble/babble/ApplicationTest.java
> refactor: 사용되지 않는 import 구문 제거

- .github/workflows/back-release.yml
- back/babble/src/main/java/gg/babble/babble/DataLoader.java
back-release.yml 문법 수정
Closes #
> refactor: 사용되지 않는 import 구문 수정

- .github/workflows/back-release.yml
- back/babble/src/main/java/gg/babble/babble/DataLoader.java
- back/babble/src/test/java/gg/babble/babble/ApplicationTest.java
>  refactor: 사용되지 않는 import 구문 수정 

- .github/workflows/back-main.yml
> chore: CICD 자동화 파일 설정 추가

- back/babble/src/main/java/gg/babble/babble/dto/request/MessageRequest.java
- back/babble/src/main/java/gg/babble/babble/dto/response/MessageResponse.java
- back/babble/src/main/java/gg/babble/babble/service/ChatService.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketChattingTest.java
> feat: message에 타입필드 추가

- back/babble/src/docs/custom-snippets/chat-send/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-send/web-socket-response.adoc
- back/babble/src/main/resources/static/docs/api-docs.html
Closes #333 
- websocket message request, response 관련 restdocs 갱신
> docs: message 에 type이 추가되어 문서 갱신

- back/babble/build.gradle
- back/babble/src/docs/custom-snippets/chat-send/web-socket-request.adoc
- back/babble/src/docs/custom-snippets/chat-send/web-socket-response.adoc
- back/babble/src/main/java/gg/babble/babble/domain/room/MaxHeadCount.java
- back/babble/src/main/resources/application-prod.properties
- back/babble/src/main/resources/application-test.properties
- back/babble/src/main/resources/db/migration/V1__init.sql
- back/babble/src/main/resources/static/docs/api-docs.html
Closes #289 
flyway로 db 마이그레이션 적용
#313 참고
> flyway로 db 마이그레이션 적용

- back/babble/src/main/resources/application-local.properties
develop 반영 사항 release로 끌어올립니다.
> fix: local 프로필이 사용하는 DB 컨테이너 IP주소 변경 (#342)

- .github/workflows/back-main.yml
* chore: 테스트 서버용 release 브랜치 생성
테스트 서버용 release 브랜치 생성
테스트 서버 자동 CI/CD를 위한 yml 파일 분리
* feat: 테스트용 WAS가 테스트용 db와 연결되도록 수정  (#54)
* chore: 테스트 서버용 release 브랜치 생성 (#52)
테스트 서버용 release 브랜치 생성
테스트 서버 자동 CI/CD를 위한 yml 파일 분리
Co-authored-by: hyeon9mak <jinha3507@gmail.com>
* chore: local properties 추가 (#53)
Co-authored-by: hyeon9mak <jinha3507@gmail.com>
* fix: local db를 localhost로 수정 (#62)
* refactor : final 키워드 삽입 (#60)
* fix: local db를 localhost로 수정 (#61)
Co-authored-by: yoonsung.jung <ybook2012@gmail.com>
* fix: db url 수정 (#64)
* refactor : final 키워드 삽입 (#60)
* fix: local db를 localhost로 수정 (#61)
* fix: db url 수정 (#63)
Co-authored-by: yoonsung.jung <ybook2012@gmail.com>
* fix: 워크플로우 파일 오타 수정
* fix: 서비스용 db ip 수정
Co-authored-by: ROOT <junroot0909@gmail.com>
Co-authored-by: unluckyjung …
> Hotfix/back/workflow (#344)

- .github/workflows/back-main.yml
- back/babble/src/main/resources/application-local.properties
> Hotfix: workflow 파일 오타 수정

- .github/workflows/back-main.yml
- back/babble/src/main/java/gg/babble/babble/service/SubscribeAuthService.java
> style: 서비스코드 import 구문 순서 수정 (#348)

- back/babble/src/main/resources/application-prod.properties
> refactor: conflict가 발생하는 application-prod.properties 파일 제거

- back/babble/src/main/resources/application-prod.properties
> feat: conflict 해결(2)

- back/babble/src/docs/asciidoc/api-docs.adoc
- back/babble/src/main/java/gg/babble/babble/controller/GameController.java
- back/babble/src/main/java/gg/babble/babble/dto/response/GameWithImageResponse.java
- back/babble/src/main/java/gg/babble/babble/service/GameService.java
- back/babble/src/main/resources/static/docs/api-docs.html
- back/babble/src/test/java/gg/babble/babble/restdocs/GameApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/GameServiceTest.java
* feat: 단일 게임 조회 기능 구현
* feat: rest-docs에 새로운 API 반영
Co-authored-by: ROOT <junroot0909@gmail.com>
Closes #
> Feature/back/single game (#361)

- back/babble/src/main/resources/db/migration/V2__add_column_deleted.sql
> fix: 사용되지 않는 컬럼 추가 sql 제거

- back/babble/src/main/resources/db/migration/V2__add_column_deleted.sql
> fix: 사용되지 않는 컬럼 추가 sql 제거 (#393)

- back/babble/src/main/resources/db/migration/V2__add_column_deleted.sql
> fix: syntax error 수정 (#395)

- .github/workflows/back-release.yml
- back/babble/src/main/java/gg/babble/babble/domain/room/Room.java
> chore: sonarCube 빌드를 한 job에서 수행하도록 수정

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
- front/package-lock.json
> test: 테스트 자동화 yml 파일 수정 (#415)

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
Co-authored-by: iborymagic <mlch8023@gmail.com>
Closes #
> test: 테스트 자동화 yml 파일 수정 (#417)

- front/src/pages/RoomList/RoomList.js
Co-authored-by: iborymagic <mlch8023@gmail.com>
Closes #
> test: 테스트 자동화 yml 파일 수정 (#419)

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
* chore: E2E테스트 자동화 테스트
Co-authored-by: iborymagic <mlch8023@gmail.com>
Closes #
> chore: 프론트 테스트 yml 수정 (#421)

- front/src/pages/RoomList/RoomList.js
* chore: E2E테스트 자동화 테스트
* chore: E2E테스트 자동화 테스트 …
> chore: E2E 테스트 자동화 테스트 (#423)

- front/cypress.json
* chore: E2E테스트 자동화 테스트
* chore: E2E테스트 자동화 테스트
* chore: …
> chore: cypress.json 파일 수정 (#425)

- front/cypress/integration/App.spec.js
- front/cypress/plugins/index.js
- front/cypress/support/commands.js
- front/cypress/support/index.js
* chore: E2E테스트 자동화 테스트
* chore: E2E테스트 자동화 테스트
* chore: …
> chore: 테스트 코드 일부 수정 (#429)

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketChattingTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/UserApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/UserServiceTest.java
> fix: 아바타 url 잘못된 경로 수정

- front/src/chunks/Participants/Participants.js
- front/src/components/Avatar/Avatar.scss
- front/src/components/Room/Room.js
- front/src/components/SpeechBubble/SpeechBubbleWithAvatar.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/GameList/GameList.js
- front/src/pages/RoomList/RoomList.js
> fix: 프로필 이미지가 출력되지 않던 버그 수정

- back/babble/src/main/java/gg/babble/babble/domain/user/User.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketChattingTest.java
- back/babble/src/test/java/gg/babble/babble/restdocs/UserApiDocumentTest.java
- back/babble/src/test/java/gg/babble/babble/service/UserServiceTest.java
> fix: 스크롤 버그 수정

- .github/workflows/front-release.yml
- front/src/pages/RoomList/RoomList.js
> chore: 프론트 수정사항 배포

- .github/workflows/front-release.yml
- front/src/pages/RoomList/RoomList.js
> chore: 테스트 자동화 임시 비활성화 (#442)

- front/src/chunks/Participants/Participants.scss
* chore: 테스트 자동화 임시 비활성화
* css: 참가자 수가 많아지는 경우 참가자 목록에 스크롤 적용
Closes #
> fix: 참가자 목록이 스크롤되지 않던 버그 수정 (#444)

- front/src/pages/ChattingRoom/ChattingRoom.scss
> fix: scroll event

- front/src/pages/ChattingRoom/ChattingRoom.scss
> fix: scroll event (#446)

- .github/workflows/front-release.yml
- front/cypress/integration/App.spec.js
- front/src/chunks/Participants/Participants.scss
- front/src/pages/ChangeNickname/ChangeNickname.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/GameList/GameList.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/RoomList/RoomList.js
Closes #450 
- 테스트용 API를 배포용으로 교체
> chore: 테스트용 API를 배포용으로 교체

- front/cypress/integration/App.spec.js
- front/src/pages/ChangeNickname/ChangeNickname.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/GameList/GameList.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/RoomList/RoomList.js
> chore: 테스트용 API를 배포용으로 교체 (#452)

- .github/workflows/front-main.yml
- .github/workflows/front-release.yml
- front/cypress/integration/App.spec.js
- front/cypress/support/index.js
- front/src/chunks/Participants/Participants.scss
- front/src/pages/ChangeNickname/ChangeNickname.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/GameList/GameList.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/RoomList/RoomList.js
Closes #
- front-main.yml에서 E2E 테스트 제거
> chore: front-main.yml에서 E2E 테스트 제거

- .github/workflows/front-main.yml
- front/cypress/support/index.js
Closes #
- front-main.yml에서 E2E 테스트 제거
> chore: front-main.yml에서 E2E 테스트 제거 (#456)

- .github/workflows/back-main-deploy.yml
- .github/workflows/back-main-test.yml
- .github/workflows/back-release-deploy.yml
- .github/workflows/back-release-test.yml
> feat: Pull Request를 보내면 테스트가 진행되도록 수정

- .github/workflows/front-release-deploy.yml
- .github/workflows/front-release-test.yml
> chore: front 테스트 자동화 파일 분리

- front/src/chunks/Participants/Participants.js
Co-authored-by: iborymagic <mlch8023@gmail.com>
Closes #
테스트의 테스트
> test: front 테스트를 테스트함

- .github/workflows/front-main.yml
- .github/workflows/front-release-deploy.yml
Closes #
- front yml 파일 distribution id 변수명 변경
> fix: front yml 파일 distribution id 변수명 변경

- .github/workflows/front-main.yml
- .github/workflows/front-release-deploy.yml
Closes #
- front yml 파일 distribution id 변수명 변경
> fix: front yml 파일 distribution id 변수명 변경 (#491)

- front/src/contexts/UserProvider.js
> test: 테스트용 파일 수정

- .github/workflows/front-main.yml
- .github/workflows/front-release-deploy.yml
- front/src/contexts/UserProvider.js
> fix: 테스트용 파일 수정

- .github/workflows/front-main.yml
> fix: front-main.yml 수정

- back/babble/src/main/java/gg/babble/babble/domain/Session.java
- back/babble/src/main/java/gg/babble/babble/domain/game/Game.java
- back/babble/src/main/java/gg/babble/babble/domain/room/Room.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketRoomUpdateTest.java
- back/babble/src/test/resources/websocket-context.sql
논리적 삭제 사용하는 Entity에 `@Where` 어노테이션 사용
Closes #
> fix: 유저가 방에서 제대로 나가지지 않는 버그 수정 (#498)

- back/babble/src/main/java/gg/babble/babble/domain/Session.java
- back/babble/src/main/java/gg/babble/babble/domain/game/Game.java
- back/babble/src/main/java/gg/babble/babble/domain/room/Room.java
- back/babble/src/test/java/gg/babble/babble/controller/WebSocketRoomUpdateTest.java
- back/babble/src/test/resources/websocket-context.sql
> fix(Chatting): 유저가 방에서 제대로 나가지지 않는 버그 수정

- .github/workflows/back-main-deploy.yml
- back/babble/src/main/java/gg/babble/babble/controller/EnterExitController.java
> fix: main 브랜치 배포시 deploy 디렉토리 내에서 동작하도록 수정

- .github/workflows/front-main.yml
> fix(workflow): main 브랜치 배포시 deploy 디렉토리내에서 동작하도록 수정

- front/cypress/integration/App.spec.js
- front/index.js
- front/src/chunks/Participants/Participants.js
- front/src/chunks/Participants/Participants.scss
- front/src/components/Footer/Footer.js
- front/src/components/Modal/Modal.js
- front/src/components/NotFound/NotFound.js
- front/src/components/ToggleNotification/ToggleNotification.js
- front/src/components/ToggleNotification/ToggleNotification.scss
- front/src/components/index.js
- front/src/constants/api.js
- front/src/constants/regex.js
- front/src/contexts/PushNotificationProvider.js
- front/src/hooks/usePushNotification.js
- front/src/hooks/useTabNotification.js
- front/src/pages/ChangeNickname/ChangeNickname.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/ChattingRoom/ChattingRoom.scss
- front/src/pages/GameList/GameList.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/RoomList/RoomList.js
> feat: 푸시 알림 on/off 기능 구현

- front/src/pages/GameList/GameList.js
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
Closes #
> feat: 줄임말에 대한 자동완성 기능 구현

- .github/workflows/back-main-deploy.yml
- .github/workflows/back-release-deploy.yml
- back/babble/src/main/java/gg/babble/babble/service/TagService.java
> refactor: workflow 파일 자바 버전 스위칭 명시적으로 변경

- .github/workflows/back-main-deploy.yml
- .github/workflows/back-release-deploy.yml
- back/babble/src/main/java/gg/babble/babble/service/TagService.java
- front/src/pages/GameList/GameList.js
> 줄임말에 대한 자동완성 기능 구현 / workflow 파일 자바 버전 스위칭 명시적으로 변경

- front/src/pages/RoomList/RoomList.js
* feat: 줄임말에 대한 자동완성 기능 구현
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
* feat: 태그 대안 이름에 대한 검색 구현
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
Closes #
> feat: 태그 대안 이름에 대한 검색 구현 (#527)

- front/index.html
* feat: 줄임말에 대한 자동완성 기능 구현
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
* chore: Google Analytics 추가
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
Co-authored-by: yoonsung.jung <ybook2012@gmail.com>
Closes #
> feat: google analytics 추가 (#529)

- .github/workflows/sonarcloud-analysis.yml
Closes #525
프론트엔드 PR인데 sonarcloud 정적 분석이 실행되는 문제 해결
없음
> feat: 백엔드 관련 pr 요청만 정적 분석하도록 수정

- back/babble/src/main/resources/application-dev.yml
> refactor: application-dev.yml 데이터베이스 설정 제거

- back/babble/src/main/java/gg/babble/babble/config/AdminAccessInterceptor.java
- back/babble/src/test/java/gg/babble/babble/restdocs/GameApiDocumentTest.java
* feat: x-forwarded-for 헤더를 사용해서 IP를 확인하도록 수정
* refactor: 불필요한 개행 제거
> feat: x-forwarded-for 헤더를 사용해서 IP를 확인하도록 수정 (#554)

- front/src/components/SpeechBubble/SpeechBubble.scss
- front/src/contexts/PushNotificationProvider.js
- front/src/pages/ChangeNickname/ChangeNickname.js
- front/src/pages/ChattingRoom/ChattingRoom.js
- front/src/pages/GameList/GameList.js
- front/src/pages/MakeRoom/MakeRoom.js
- front/src/pages/RoomList/RoomList.js
- front/webpack.config.js
* feat: 줄임말에 대한 자동완성 기능 구현
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
* fix: 대화창 말풍선 초상화 우측에 gap 추가
* refactor: api 호출부에 에러 핸들링 추가
* fix: safari에서 채팅 창이 열리지 않는 문제 해결
* fix: PushNotification의 Notification.permission 가드 수정
Co-authored-by: yoonsung.jung <ybook2012@gmail.com>
Co-authored-by: An Hyun Cheol <iborymagic@users.noreply.github.com>
Co-authored-by: ROOT <junroot0909@gmail.com>
Closes #544 #546
> fix: 모바일 사파리와 카카오톡 브라우저에서 페이지가 열리지 않던 버그 수정 (#556)

- back/babble/src/main/java/gg/babble/babble/controller/BabbleAdvice.java
Closes #558 
- 로깅 파일이 남지 않는 문제를 해결했습니다.
- 예상치 못한 예외 발생시 스택 트레이스를 로그로 남기도록 수정했습니다. 디버깅시 어떤 문제가 발생했는지 확실히 하기 위해서입니다.
[수정 전]
[수정 후]
logback에 logger 이름을 패키지 네임으로 지정해뒀을 경우, 클래스 내에 로그 생성시 `getClass().getSimpleName()` 로 지정하면 패키지 이름이 읽어지지 않는 문제가 있었습니다. 아래와 같은 방법으로 로거를 만들어 해결했습니다.
```java
LoggerFactory.getLogger(BabbleAdvice.class);
```
> fix: 로깅이 제대로 남지 않는 문제 해결

- .github/workflows/back-release-deploy.yml
- back/babble/src/main/resources/application-dev.yml
- front/src/chunks/AdminManagement/AdminManagement.js
- front/src/chunks/AdminManagement/AdminManagement.scss
- front/src/chunks/AdminManagement/AdminManagement.stories.js
- front/src/chunks/GameManagement/GameManagement.js
- front/src/chunks/GameManagement/GameManagement.scss
- front/src/chunks/GameManagement/GameManagement.stories.js
- front/src/components/ImagePreview/ImagePreview.scss
- front/src/components/ImageRegister/ImageRegister.scss
- front/src/components/NameList/NameList.js
- front/src/components/NameList/NameList.scss
- front/src/components/SpeechBubble/SpeechBubble.stories.js
- front/style/_functions.scss
- front/style/_mixins.scss
- front/style/_variables.scss
> 게임 관리 컴포넌트 / 운영자 관리 컴포넌트 /  TEST 인스턴스 분리에 따른 리팩토링

- back/babble/src/test/resources/application.yml
> refactor: test profile 변경

- back/babble/src/main/java/gg/babble/babble/domain/game/AlternativeGameNames.java
- back/babble/src/main/java/gg/babble/babble/domain/repository/SessionRepository.java
- back/babble/src/main/java/gg/babble/babble/domain/room/Rooms.java
- back/babble/src/main/java/gg/babble/babble/domain/room/Sessions.java
- back/babble/src/main/java/gg/babble/babble/domain/room/TagRegistrationsOfRoom.java
- back/babble/src/main/java/gg/babble/babble/domain/tag/AlternativeTagNames.java
- back/babble/src/main/java/gg/babble/babble/domain/tag/TagRegistrationsOfTag.java
- back/babble/src/main/java/gg/babble/babble/service/RoomService.java
- back/babble/src/main/resources/application.yml
- back/babble/src/test/java/gg/babble/babble/domain/repository/SessionRepositoryTest.java
- back/babble/src/test/java/gg/babble/babble/domain/repository/TagRepositoryTest.java
- back/babble/src/test/java/gg/babble/babble/service/GameServiceTest.java
- back/babble/src/test/java/gg/babble/babble/service/RoomServiceTest.java
- back/babble/src/test/resources/application.yml
> refactor: n + 1 문제 해결 (#739)

- back/babble/src/docs/custom-snippets/chat-room-connect/web-socket-response.adoc
- back/babble/src/test/java/gg/babble/babble/restdocs/websocket/ChattingTest.java
- front/package-lock.json
- front/package.json
- front/src/hooks/useTheme.js
- front/src/utils/storage.js
- front/style/global.scss
> fix: 다라쓰 다크모드 실시간 전환 적용

- README.md
> docs: release 브랜치 설명 추가
